[project]
name = "final-version"
version = "0.1.0"
description = "JORAM, Beginning from 2020"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pip>=25.3",
    "pymupdf>=1.26.6",
    "pymupdf4llm>=0.2.2",
    "spacy>=3.8.9",
]
